 version: '3'

 services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRESDB: main
    ports: [5432]

  redis:
    image: redis:5-alpine
    ports: [6379]